import { useState, useEffect } from 'react';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';
import AdminLayout from '../components/AdminLayout';

const SuperAdminPayouts = () => {
    const { user } = useAuth();
    const [stats, setStats] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');
    const [processing, setProcessing] = useState(null);

    const fetchStats = async () => {
        try {
            const config = { headers: { Authorization: `Bearer ${user.token}` } };
            const { data } = await axios.get('/api/revenue/admin', config);
            setStats(data);
            setLoading(false);
        } catch (err) {
            setError(err.response?.data?.message || 'Failed to fetch payout stats');
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchStats();
    }, []);

    const handlePayout = async (ownerId, ownerName) => {
        if (!window.confirm(`Are you sure you want to process the payout for ${ownerName}? This will mark all their pending completed bookings as Paid.`)) {
            return;
        }

        setProcessing(ownerId);
        try {
            const config = { headers: { Authorization: `Bearer ${user.token}` } };
            await axios.put(`/api/revenue/admin/payout/${ownerId}`, {}, config);
            alert(`Payout processed successfully for ${ownerName}`);
            fetchStats(); // Refresh the table
        } catch (err) {
            alert(err.response?.data?.message || 'Failed to process payout');
        } finally {
            setProcessing(null);
        }
    };

    return (
        <AdminLayout title="Owner Payouts" role="super_admin">
            <div className="bg-white rounded-lg shadow-sm border border-gray-200">
                <div className="px-6 py-4 border-b border-gray-200">
                    <h2 className="text-lg font-bold text-gray-800">Revenue & Payout Management</h2>
                    <p className="text-sm text-gray-500">Track total revenue generated by owners and process pending payouts.</p>
                </div>

                {loading ? (
                    <div className="p-8 text-center text-gray-500">Loading payout data...</div>
                ) : error ? (
                    <div className="p-8 text-center text-red-500">{error}</div>
                ) : (
                    <div className="overflow-x-auto">
                        <table className="w-full text-left border-collapse">
                            <thead>
                                <tr className="bg-gray-50 border-b border-gray-200 text-xs uppercase tracking-wider text-gray-500">
                                    <th className="px-6 py-4 font-semibold">Owner Name</th>
                                    <th className="px-6 py-4 font-semibold">Email</th>
                                    <th className="px-6 py-4 font-semibold text-right">Total Generated</th>
                                    <th className="px-6 py-4 font-semibold text-right">Paid Out</th>
                                    <th className="px-6 py-4 font-semibold text-right">Pending Payout</th>
                                    <th className="px-6 py-4 font-semibold text-center">Actions</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-gray-100">
                                {stats.length === 0 ? (
                                    <tr>
                                        <td colSpan="6" className="px-6 py-8 text-center text-gray-500">
                                            No owners found or no revenue data available.
                                        </td>
                                    </tr>
                                ) : (
                                    stats.map((stat) => (
                                        <tr key={stat.ownerId} className="hover:bg-gray-50 transition-colors">
                                            <td className="px-6 py-4 font-medium text-gray-900">{stat.name}</td>
                                            <td className="px-6 py-4 text-sm text-gray-500">{stat.email}</td>
                                            <td className="px-6 py-4 text-sm font-bold text-gray-700 text-right">
                                                Rs. {stat.totalGenerated.toLocaleString()}
                                            </td>
                                            <td className="px-6 py-4 text-sm font-bold text-green-600 text-right">
                                                Rs. {stat.totalPaid.toLocaleString()}
                                            </td>
                                            <td className="px-6 py-4 text-sm font-bold text-orange-600 text-right">
                                                Rs. {stat.totalPending.toLocaleString()}
                                            </td>
                                            <td className="px-6 py-4 text-center">
                                                <button
                                                    onClick={() => handlePayout(stat.ownerId, stat.name)}
                                                    disabled={stat.totalPending === 0 || processing === stat.ownerId}
                                                    className={`px-4 py-2 text-sm font-bold rounded shadow-sm transition-colors ${stat.totalPending === 0
                                                            ? 'bg-gray-100 text-gray-400 cursor-not-allowed'
                                                            : 'bg-blue-600 text-white hover:bg-blue-700'
                                                        }`}
                                                >
                                                    {processing === stat.ownerId ? 'Processing...' : 'Process Payout'}
                                                </button>
                                            </td>
                                        </tr>
                                    ))
                                )}
                            </tbody>
                        </table>
                    </div>
                )}
            </div>
        </AdminLayout>
    );
};

export default SuperAdminPayouts;
